using Gateway.Shared.ChatTransit;
using Gateway.Shared.ChatTransit.Hints;
using Gateway.Shared.ChatTransit.Inbound;
using Gateway.Shared.ChatTransit.Mapping;
using Gateway.Shared.ChatTransit.Outbound;
using Microsoft.Extensions.AI;
using System.Text;
using System.Text.Json;

namespace ChatTransit.Tests.Roundtrip;

/// <summary>
/// Round-trip tests for Gemini-specific protocol details that the model
/// validates on the next turn: <c>functionCall.id</c> (Gemini 3+),
/// <c>thoughtSignature</c>, and <c>videoMetadata</c>.
/// </summary>
public class GeminiIdAndSignatureRoundtripTests
{
    [Fact]
    public void FunctionCall_Id_SurvivesRoundTrip_AndIsEchoedOnFunctionResponse()
    {
        var json = """
        {
          "contents": [
            {"role": "model", "parts": [
              {"functionCall": {"id": "fc_abc123", "name": "get_weather", "args": {"city": "Paris"}}}
            ]},
            {"role": "user", "parts": [
              {"functionResponse": {"id": "fc_abc123", "name": "get_weather", "response": {"temp": 23}}}
            ]}
          ],
          "tools": [{"functionDeclarations": [{"name": "get_weather"}]}]
        }
        """;
        var transit = new GeminiInboundDecoder().Decode(Encoding.UTF8.GetBytes(json));

        var fcc = transit.Messages.SelectMany(m => m.Contents)
            .OfType<FunctionCallContent>().Single();
        fcc.CallId.Should().Be("fc_abc123");
        fcc.Name.Should().Be("get_weather");

        var frc = transit.Messages.SelectMany(m => m.Contents)
            .OfType<FunctionResultContent>().Single();
        frc.CallId.Should().Be("fc_abc123");

        var encoded = new GeminiOutboundEncoder().Encode(transit);
        using var doc = JsonDocument.Parse(encoded);
        var contents = doc.RootElement.GetProperty("contents");

        var modelCall = contents.EnumerateArray()
            .First(c => c.GetProperty("role").GetString() == "model")
            .GetProperty("parts")[0].GetProperty("functionCall");
        modelCall.GetProperty("id").GetString().Should().Be("fc_abc123");
        modelCall.GetProperty("name").GetString().Should().Be("get_weather");

        var userResponse = contents.EnumerateArray()
            .First(c => c.GetProperty("role").GetString() == "user")
            .GetProperty("parts")[0].GetProperty("functionResponse");
        userResponse.GetProperty("id").GetString().Should().Be("fc_abc123");
        userResponse.GetProperty("name").GetString().Should().Be("get_weather");
    }

    [Fact]
    public void FunctionCall_NoId_DoesNotEmitIdField()
    {
        var json = """
        {
          "contents": [
            {"role": "model", "parts": [
              {"functionCall": {"name": "get_weather", "args": {"city": "Paris"}}}
            ]}
          ],
          "tools": [{"functionDeclarations": [{"name": "get_weather"}]}]
        }
        """;
        var transit = new GeminiInboundDecoder().Decode(Encoding.UTF8.GetBytes(json));
        var encoded = new GeminiOutboundEncoder().Encode(transit);
        using var doc = JsonDocument.Parse(encoded);
        var fc = doc.RootElement.GetProperty("contents")[0]
            .GetProperty("parts")[0].GetProperty("functionCall");
        fc.TryGetProperty("id", out _).Should().BeFalse(
            "callId is auto-generated by MEAI; without a wire id we must not emit one");
    }

    [Fact]
    public void ThoughtSignature_OnThought_SurvivesRoundTrip()
    {
        const string sig = "AbCdEfGh12345...";
        var json = $$"""
        {
          "contents": [
            {"role": "model", "parts": [
              {"text": "internal reasoning", "thought": true, "thoughtSignature": "{{sig}}"},
              {"text": "Hello world"}
            ]}
          ]
        }
        """;
        var transit = new GeminiInboundDecoder().Decode(Encoding.UTF8.GetBytes(json));

        var thinking = transit.Messages[0].Contents.First(ThinkingMapper.IsThinkingContent);
        ThinkingMapper.GetGeminiThoughtSignature(thinking).Should().Be(sig);

        var encoded = new GeminiOutboundEncoder().Encode(transit);
        using var doc = JsonDocument.Parse(encoded);
        var thoughtPart = doc.RootElement.GetProperty("contents")[0]
            .GetProperty("parts").EnumerateArray()
            .First(p => p.TryGetProperty("thought", out var t) && t.GetBoolean());
        thoughtPart.GetProperty("thoughtSignature").GetString().Should().Be(sig);
    }

    [Fact]
    public void ThoughtSignature_OnFunctionCall_SurvivesRoundTrip()
    {
        const string sig = "FunctionCallSigOpaque";
        var json =
            "{\"contents\":[{\"role\":\"model\",\"parts\":[" +
            "{\"functionCall\":{\"id\":\"fc_1\",\"name\":\"lookup\",\"args\":{}}," +
            $"\"thoughtSignature\":\"{sig}\"}}]}}]}}";
        var transit = new GeminiInboundDecoder().Decode(Encoding.UTF8.GetBytes(json));
        var fcc = transit.Messages.SelectMany(m => m.Contents).OfType<FunctionCallContent>().Single();
        ThinkingMapper.GetGeminiThoughtSignature(fcc).Should().Be(sig);

        var encoded = new GeminiOutboundEncoder().Encode(transit);
        using var doc = JsonDocument.Parse(encoded);
        var part = doc.RootElement.GetProperty("contents")[0].GetProperty("parts")[0];
        part.GetProperty("thoughtSignature").GetString().Should().Be(sig);
    }

    [Fact]
    public void AnthropicThinkingSignature_CrossEncodesTo_GeminiThoughtSignature()
    {
        // Cross-protocol: a Claude-Code (Anthropic) caller routed onto a
        // Gemini-native backend (Antigravity → PA → Claude/Vertex). The opaque
        // thinking signature must survive Anthropic-in → Gemini-out, otherwise PA
        // emits a signature-less Anthropic thinking block and the Vertex adapter
        // 400s with "messages.N.content.0.thinking.signature: Field required".
        const string sig = "ErcBCkgIBhABGAI...opaque";
        var json = $$"""
        {
          "model": "claude-sonnet-4-6",
          "messages": [
            { "role": "assistant", "content": [
              { "type": "thinking", "thinking": "internal reasoning", "signature": "{{sig}}" },
              { "type": "text", "text": "Hello world" }
            ] },
            { "role": "user", "content": "continue" }
          ]
        }
        """;
        var transit = new AnthropicInboundDecoder().Decode(Encoding.UTF8.GetBytes(json));

        var thinking = transit.Messages.SelectMany(m => m.Contents)
            .First(ThinkingMapper.IsThinkingContent);
        ThinkingMapper.GetAnthropicSignature(thinking).Should().Be(sig);

        var encoded = new GeminiOutboundEncoder().Encode(transit);
        using var doc = JsonDocument.Parse(encoded);
        var thoughtPart = doc.RootElement.GetProperty("contents").EnumerateArray()
            .SelectMany(c => c.GetProperty("parts").EnumerateArray())
            .First(p => p.TryGetProperty("thought", out var t) && t.GetBoolean());
        thoughtPart.GetProperty("thoughtSignature").GetString().Should().Be(sig,
            "the Anthropic signature must be re-emitted as the Gemini thoughtSignature");
    }

    [Fact]
    public void GenerationConfig_PenaltiesAndExtras_RoundTrip()
    {
        var json = """
        {
          "contents": [{"role": "user", "parts": [{"text": "hi"}]}],
          "generationConfig": {
            "temperature": 0.7,
            "topP": 0.9,
            "topK": 40,
            "maxOutputTokens": 512,
            "presencePenalty": 0.5,
            "frequencyPenalty": -0.3,
            "candidateCount": 1,
            "responseMimeType": "application/json",
            "thinkingConfig": {"thinkingBudget": 1024, "includeThoughts": true}
          },
          "safetySettings": [{"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_ONLY_HIGH"}]
        }
        """;
        var transit = new GeminiInboundDecoder().Decode(Encoding.UTF8.GetBytes(json));
        var encoded = new GeminiOutboundEncoder().Encode(transit);
        using var doc = JsonDocument.Parse(encoded);
        var cfg = doc.RootElement.GetProperty("generationConfig");
        cfg.GetProperty("presencePenalty").GetDouble().Should().BeApproximately(0.5, 1e-9);
        cfg.GetProperty("frequencyPenalty").GetDouble().Should().BeApproximately(-0.3, 1e-9);
        cfg.GetProperty("candidateCount").GetInt32().Should().Be(1);
        cfg.GetProperty("responseMimeType").GetString().Should().Be("application/json");
        cfg.GetProperty("thinkingConfig").GetProperty("thinkingBudget").GetInt32().Should().Be(1024);
        cfg.GetProperty("thinkingConfig").GetProperty("includeThoughts").GetBoolean().Should().BeTrue();
        doc.RootElement.GetProperty("safetySettings").GetArrayLength().Should().Be(1);
    }
}
